#!/bin/bash

if [ ! -d "out" ]; then
  mkdir out
fi

g++ -oout/main main.cpp -nostdlib -static
if [ $? -eq 0 ]; then
	echo "Compilation successful. Running the program...
	"
	./out/main
else
	echo "Compilation failed."
fi
